### ISSUE TITLE
I see the alarm scheduling was successful message in success, but not working

### ISSUE THREAD

**Issue by Yildiraygemuk** [baekgol/react-native-alarm-manager#1]
I see the alarm scheduling was successful message in success. When I list the alarms, that alarm appears, but there is no alarm or notification that rings when the time I set comes. What is the reason?

When I query my alarm list I see this:

{"alarm_activate": true, "alarm_icon": "icon", "alarm_id": 3, "alarm_noti_removable": true, "alarm_sound": "sound", "alarm_sound_loop": true, "alarm_text": "text", "alarm_time": "22:08:00", "alarm_title": "title", "alarm_vibration": true}

My codes is here :

const alarm = {
  alarm_time: "22:08:00",   // HH:mm:00
  alarm_title: 'title',
  alarm_text: 'text',
  alarm_sound: 'sound',   // sound.mp3
  alarm_icon: 'icon',     // icon.png
  alarm_sound_loop: true,
  alarm_vibration: true,
  alarm_noti_removable: true,
  alarm_activate: true
};
Alarm.schedule(
  alarm,
  success => console.log("sc",success),  // success message
  fail => console.log("fl",fail)         // fail message
);
Alarm.searchAll(
  success => console.log("listsuccs",success),  // alarm list
  fail => console.log("listerr",fail)         // fail message
);

**Comment by baekgol** [comment]
Hello @Yildiraygemuk !
Perhaps officially you are the first to use my package.
Thank you for using it and leaving a question.

Have you tried following this one in README?
[Manipulating codes in your project](https://github.com/baekgol/react-native-alarm-manager#manipulating-codes-in-your-project)

If that doesn't work, I can think of two ways.
First, after [Create resource directory](https://github.com/baekgol/react-native-alarm-manager#create-resource-directory), You have to put the icon and music file you want to use in the corresponding path.

Second, make sure you have an icon file or a sound file.
```javascirpt
const alarm = {
  alarm_time: "22:08:00", // HH:mm:00
  alarm_title: 'title',
  alarm_text: 'text',
  alarm_sound: 'sound', // sound.mp3
  alarm_icon: 'icon', // icon.png
  alarm_sound_loop: true,
  alarm_vibration: true,
  alarm_noti_removable: true,
  alarm_activate: true
};
```

If you do this, you must have files in those directories.
```
project/app/src/main/res/raw/sound.mp3       // alarm sound
project/app/src/main/res/drawable/icon.png  // notification icon
```

If you see the list output when you query the alarm list, I think the alarm is scheduled properly.
Please check the points above and hope it works.

**Comment by Yildiraygemuk** [comment]
I did ! Thank you. It worked when I manipulated the codes.
