### ISSUE TITLE
How can i listen the notification alarm

### ISSUE THREAD

**Issue by Ahmet-Kutuk** [baekgol/react-native-alarm-manager#17]
How do I know when the alarm starts on react native side?

**Comment by baekgol** [comment]
Hello @Ahmet-Kutuk.
I'm sorry but, this library do not support **Listener Functions** like onAlarmStart().
Thanks to you, I realized I was overlooking that Listener features didn't exist.
I'll try to take it into consideration in a future update.
Thank you.
