### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNativeAlarmManager.default.schedule')

### ISSUE THREAD

**Issue by Altanis** [baekgol/react-native-alarm-manager#18]
https://stackoverflow.com/questions/73431786/typeerror-null-is-not-an-object-evaluating-reactnativealarmmanager-default-s

**Comment by ekiziltas** [comment]
+1

> https://stackoverflow.com/questions/73431786/typeerror-null-is-not-an-object-evaluating-reactnativealarmmanager-default-s

**Comment by franciscomorais** [comment]
only android :/
