### ISSUE TITLE
How do i set alarm at Particular Day of the Week (for example only alarm for Monday and Tuesday etc.) ? And How Do i set Alarm Every Day?

### ISSUE THREAD

**Issue by ApWin** [baekgol/react-native-alarm-manager#2]

**Comment by baekgol** [comment]
Hi @ApWin.
Unfortunately, there is no function that set an alarm at particular day in this library.
Only you can do is set an alarm through time.
But, you can set an alarm for every day.
Just choose the time you want and keep your switch on.
Unless the switch is off, the alarm will be triggered at the time you set.
