### ISSUE TITLE
Is it possible to use the sound from uri?

### ISSUE THREAD

**Issue by fajarardiyanto** [baekgol/react-native-alarm-manager#7]

**Comment by baekgol** [comment]
Hello @fajarardiyanto!
You can't use the sound from uri in this library.
You can only use the sound that has already saved to the [directory](https://github.com/baekgol/react-native-alarm-manager#create-resource-directory).
Thank you.

**Comment by fajarardiyanto** [comment]
can i get sound from download dir?

**Comment by baekgol** [comment]
I'm sorry but I don't understand what download dir is.
If the download dir you are talking about is "project/app/src/main/res/raw" then you can get the sound.
Just put the sound file you have in that path and use it.
